version: '3'

services:
  web:
    build: web
    ports:
      - "${EMBEDDED_ILIAS_PORT}:80"
    expose:
      - "80"
    volumes:
      - ./web/ILIAS:/var/www/html/ILIAS
    networks:
      - net

  db:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: ilias
    networks:
      - net

  master:
    build: robot
    ports:
      - "${TESTILIAS_PORT}:80"
    expose:
      - "80"
    volumes:
      - ./robot/files:/files
    working_dir: /files
    entrypoint: python3 -m testilias --master $ILIASTEST_ARGUMENTS
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING='utf8'
    networks:
      - net
  
  machine:
    build: robot
    volumes:
      - ./robot/files:/files
    working_dir: /files
    entrypoint: python3 -m testilias --machine $ILIASTEST_ARGUMENTS
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING='utf8'
    networks:
      - net

networks:
  net:
    driver: bridge
