version: '3'

services:
  web:
    build:
      context: docker/web
      args:
        TILTR_PHP_IMAGE: "${TILTR_PHP_IMAGE}"
    ports:
      - "${TILTR_EMBEDDED_ILIAS_PORT}:80"
    expose:
      - "80"
    volumes:
      - ./data/ILIAS:/var/www/html/ILIAS
      - ./data/tmp/iliastemp:/var/ilias/data/ilias/temp
    networks:
      - net

  db:
    build:
      context: docker/db
      args:
        TILTR_ILIAS_DB_VERSION: ${TILTR_ILIAS_DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: ilias
    networks:
      - net

  master:
    build: docker/machine
    ports:
      - "${TILTR_PORT}:8080"
    expose:
      - "8080"
    volumes:
      - ./docker/machine/app:/tiltr/app
      - ./data/tests:/tiltr/tests
      - ./data/ILIAS:/tiltr/ILIAS
      - ./data/tmp:/tiltr/tmp
    working_dir: /tiltr/app
    entrypoint: python3 -m tiltr --master $TILTR_ARGUMENTS
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING='utf8'
    networks:
      - net
  
  machine:
    build: docker/machine
    volumes:
      - ./docker/machine/app:/tiltr/app
      - ./data/tests:/tiltr/tests
    working_dir: /tiltr/app
    entrypoint: python3 -m tiltr --machine $TILTR_ARGUMENTS
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING='utf8'
    networks:
      - net

  selenium-chrome:
    image: selenium/standalone-chrome:3.141.59-europium
    networks:
    - net
    expose:
    - "4444"
    shm_size: 2G
    restart: always
    environment:
      JAVA_OPTS: "-Dselenium.LOGGER.level=WARNING"
    volumes:
      - /dev/shm:/dev/shm
      - /tmp:/tmp

  selenium-firefox:
    image: selenium/standalone-firefox:3.141.59-europium
    networks:
    - net
    expose:
    - "4444"
    shm_size: 2G
    restart: always
    environment:
      JAVA_OPTS: "-Dselenium.LOGGER.level=WARNING"
    volumes:
      - /dev/shm:/dev/shm
      - /tmp:/tmp

networks:
  net:
    driver: bridge
