version: '3'

services:
  web:
    build: web
    ports:
      - "${EMBEDDED_ILIAS_PORT}:80"
    expose:
      - "80"
    volumes:
      - ./web/ILIAS:/var/www/html/ILIAS
    networks:
      - net

  db:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: ilias
    volumes:
      - db-data-volume:/var/lib/mysql
    networks:
      - net

  master:
    build: robot
    ports:
      - "${TESTILIAS_PORT}:8080"
    expose:
      - "8080"
    volumes:
      - ./robot/files:/files
    working_dir: /files
    entrypoint: python3 -m testilias --master $ILIASTEST_ARGUMENTS
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING='utf8'
    networks:
      - net
  
  machine:
    build: robot
    volumes:
      - ./robot/files:/files
    working_dir: /files
    entrypoint: python3 -m testilias --machine $ILIASTEST_ARGUMENTS
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING='utf8'
    networks:
      - net

  selenium-chrome:
    image: selenium/standalone-chrome:3.141.59-europium
    networks:
    - net
    expose:
    - "4444"
    shm_size: 2G
    restart: always
    environment:
      JAVA_OPTS: "-Dselenium.LOGGER.level=WARNING"
    volumes:
      - /dev/shm:/dev/shm
      - /tmp:/tmp

  selenium-firefox:
    image: selenium/standalone-firefox:3.141.59-europium
    networks:
    - net
    expose:
    - "4444"
    shm_size: 2G
    restart: always
    environment:
      JAVA_OPTS: "-Dselenium.LOGGER.level=WARNING"
    volumes:
      - /dev/shm:/dev/shm
      - /tmp:/tmp

volumes:
  db-data-volume:

networks:
  net:
    driver: bridge
